

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    

install:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
- python tests/base/test_direc.py
- python tests/base/test_map.py
- python tests/base/test_point.py
- python tests/base/test_pos.py
- python tests/base/test_snake.py
