

environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    

install:
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
- python tests/test_gui.py

